[tool.poetry]
name = "rpi-remote-server"
version = "0.1.0"
description = ""
authors = ["Radics Aron <radics.aron.jozsef@gmail.com>"]
readme = "README.md"
packages = [{include = "tools"}]

[tool.poetry.dependencies]
python = "^3.7"
Flask = "^2.2.2"
paramiko = "^2.12.0"
requests = "^2.28.1"
gunicorn = "^20.1.0"
SQLAlchemy = "^1.4.44"
UPnPy = "^1.1.8"

[tool.poetry.scripts]
forward = 'tools.forward:main'
add-user = 'tools.add_user:main'
generate-secret = 'tools.generate_secret:main'


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
