import os


PORT_RANGE_START = os.environ["PORT_RANGE_START"]
PORT_RANGE_END = os.environ["PORT_RANGE_END"]
CUSTOM_MESSAGES = os.environ["CUSTOM_MESSAGES"].split(";")
ADMIN_USERNAME = os.environ["ADMIN_USERNAME"]
ADMIN_PASSWORD = os.environ["ADMIN_PASSWORD"]
